[package]
name = "simplemusicgui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.7"

simpleaudioparser = { path = "../2023-01-29-parsing" }
